### ISSUE TITLE
Show dark and light at the same time

### ISSUE THREAD

**Issue by bertob** [CleoMenezesJr/Aurea#12]
I noticed that when actually iterating on brand colors or sharing them online you kinda need both dark and light at the same time. I think it'd make sense to just show the dark banner below the light one, like the [web previewer](https://docs.flathub.org/banner-preview/) does.

**Comment by CleoMenezesJr** [comment]
So do we need a new mockup?

**Comment by bertob** [comment]
How about this?

![banner-preview2](https://github.com/CleoMenezesJr/Aurea/assets/1908896/2ccfc597-a4ea-4f5c-9232-62f1193d7fa5)

Since the size gets a bit huge with two I think it'd be good to make the banners adaptive, same as on the Flathub website. At narrower sizes the screenshot is dropped. I'm not sure what options we have to implement something like this in GTK, maybe Adw breakponts could work for some of this?

**Comment by CleoMenezesJr** [comment]
Easy-peasy lemon squeeze. When I have some time, I will do this. The breakpoint had already been made, but I removed it. I just need to revert the commit.

**Comment by CleoMenezesJr** [comment]
How about it?
[Screencast from 2024-04-10 21-31-02.webm](https://github.com/CleoMenezesJr/Aurea/assets/54215258/3fd1e6a0-5f07-4c04-be55-b272be7826d4)
