### ISSUE TITLE
Subtitle styling

### ISSUE THREAD

**Issue by bertob** [CleoMenezesJr/Aurea#14]
The subtitle is currently bold and pretty large, I'd style it more like GNOME Software and Flathub do:

![image](https://github.com/CleoMenezesJr/Aurea/assets/1908896/771d8eef-4d01-4ceb-beaf-391fb8cd1edd)

![image](https://github.com/CleoMenezesJr/Aurea/assets/1908896/5731f3b1-035a-4339-b295-3ed508bd9e3a)

**Comment by CleoMenezesJr** [comment]
![image](https://github.com/CleoMenezesJr/Aurea/assets/54215258/8bac22d5-b58a-4648-ba6e-792bb8b3dd51)
