### ISSUE TITLE
Huge vertical offset on some screenshots

### ISSUE THREAD

**Issue by bertob** [CleoMenezesJr/Aurea#24]
[This app](https://github.com/blissd/fotema)'s screenshot has a huge amount of vertical offset, not sure why/how:

![image](https://github.com/CleoMenezesJr/Aurea/assets/1908896/3665a2d7-4f12-42ad-9452-e0d4507adc18)

**Comment by CleoMenezesJr** [comment]
I definitely need to refactor the image cropping algorithm.

**Comment by CleoMenezesJr** [comment]
I changed the image cropping algorithm a little to be based on the card size. From what I tested here, it worked much better.
![image](https://github.com/CleoMenezesJr/Aurea/assets/54215258/a193cc8f-afc1-493f-b06f-76ae34a458d0)
[Screencast from 2024-05-31 00-35-37.webm](https://github.com/CleoMenezesJr/Aurea/assets/54215258/9e18dbb5-9756-4251-8d6a-babfa529f92e)
