### ISSUE TITLE
Reload metainfo on F5

### ISSUE THREAD

**Issue by agx** [CleoMenezesJr/Aurea#27]
Thanks for this helpful app!

Similar to reloading a web page it would nice if aurea would reload the current metainfo file when pressing F5 so when toying with different colors one doesn't have to go via "open". 

An alternative would be to have a file monitor and reload automatically on changes.

**Comment by CleoMenezesJr** [comment]
Now it's possible to reload using F5 or clicking Reload.

[Screencast from 2024-08-27 23-17-45.webm](https://github.com/user-attachments/assets/140c2f0a-b4d0-419f-97eb-5e1b9ab29414)

I will think about whether it is worth monitoring changes because during editing there may be programming errors.

**Comment by CleoMenezesJr** [comment]
Yeah, that's really useful.
[Screencast from 2024-08-28 22-13-32.webm](https://github.com/user-attachments/assets/e881a6d1-552f-418b-a150-ff62c2e321b4)
