### ISSUE TITLE
App crashes on apps without branding

### ISSUE THREAD

**Issue by A6GibKm** [CleoMenezesJr/Aurea#5]
```
Application started at 19:55:02
Traceback (most recent call last):
  File "/app/share/aurea/aurea/window.py", line 102, in open_file_complete
    self.branding_colors = self.get_branding_colors(xml_tree)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/aurea/aurea/window.py", line 240, in get_branding_colors
    light_color = branding.find('./color[@scheme_preference="light"]').text
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

```

**Comment by CleoMenezesJr** [comment]
Which app did you try it with? Are you using the latest commit? Here I have already opened several without branding colors without any problems.

![image](https://github.com/CleoMenezesJr/Aurea/assets/54215258/ad8bc678-a0ed-42d2-8625-a4027fdceb2c)

**Comment by A6GibKm** [comment]
From Lorem. I though it was actually missing branding but it did have it, and if I am not mistake, it is following the spec.
```
  <branding>
    <!-- Blue 4 in dark, matches project emblem -->
    <color type="primary">#1c71d8</color>
  </branding>
```

**Comment by A6GibKm** [comment]
From the [spec](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-branding) scheme_preference is optional. 

On a similar note, ideally this does should not crash even if the xml contains only garbage.
