### ISSUE TITLE
Screenshot placement is a bit odd  on small screenshots

### ISSUE THREAD

**Issue by A6GibKm** [CleoMenezesJr/Aurea#6]
![image](https://github.com/CleoMenezesJr/Aurea/assets/11528996/3b5067f2-cfca-4f97-9e74-ed3a6d1b68f7)

**Comment by CleoMenezesJr** [comment]
This needs design. Maybe, depending on the size of the image, place it in the middle.
ping @bertob

**Comment by CleoMenezesJr** [comment]
I was thinking, taking into account that it is about being a banner preview, this shows that, in fact, the screenshot is not ok to be shown on the banner and a different one should be used. Bottles, for example, [makes a collage of screenshots](https://dl.flathub.org/media/com/usebottles/bottles/0b10f4fe6467781437697bf86e2a7cd3/screenshots/image-1_1248x728@1.png)

**Comment by A6GibKm** [comment]
Imo just putting the topleft corner of the image in a fixed position should fix it. This is kinda hard to do with a picture, i will see what I can do.

**Comment by CleoMenezesJr** [comment]
I don't think the problem is repositioning things, because it wouldn't be difficult to do, I just think we shouldn't create exceptions when the problem is the information being used.  Like, move the summary because the app uses more than 200 characters (which is bad).

**Comment by bertob** [comment]
I agree that we'll need some kind of solution for smaller windows, but this needs to be coordinated with Flathub website so the behavior is predictable for app developers.

My feeling is that vertically centering windows below a certain height (e.g. 500px or so?) would work here.

**Comment by CleoMenezesJr** [comment]
> I agree that we'll need some kind of solution for smaller windows, but this needs to be coordinated with Flathub website so the behavior is predictable for app developers, cc @razzeee
> 
> My feeling is that vertically centering windows below a certain height (e.g. 500px or so?) would work here.

How does the Emblem look on the Flathub banner currently?

**Comment by razzeee** [comment]
![image](https://github.com/CleoMenezesJr/Aurea/assets/5943908/5fda7457-1244-4daf-8cb7-48719027f952)

**Comment by bertob** [comment]
Yeah, I feel like centering vertically would work nicely here.

**Comment by CleoMenezesJr** [comment]
How about it?

https://github.com/CleoMenezesJr/Aurea/assets/54215258/3fc6ac88-a000-48fd-9920-13c21f2d56fe

**Comment by bertob** [comment]
> How about that?
> Kooha-2024-03-30-13-31-58.mp4

Yeah I don't think that works without centering, it looks off-balance.

**Comment by CleoMenezesJr** [comment]
![image](https://github.com/CleoMenezesJr/Aurea/assets/54215258/1533d49b-014d-4985-9132-74de4c1f3c9f)

**Comment by bertob** [comment]
I guess this could work with some adjustments to the vertical spacing on the left side.
